"""GPX Export Service - Converts route data to GPX format for fitness apps."""

from datetime import datetime, timezone
from typing import Optional


def generate_gpx(
    route_geojson: dict,
    name: str,
    distance_m: float,
    duration_s: Optional[float] = None,
    creator: str = "DrawMyRoute"
) -> str:
    """
    Generate a GPX 1.1 file from a GeoJSON LineString route.
    
    Args:
        route_geojson: GeoJSON LineString with coordinates [[lng, lat], ...]
        name: Route name (e.g., "Heart Route")
        distance_m: Total route distance in meters
        duration_s: Optional estimated duration in seconds
        creator: Application name for GPX creator attribute
    
    Returns:
        GPX XML string ready for download
    """
    coordinates = route_geojson.get("coordinates", [])
    
    if not coordinates:
        raise ValueError("Route contains no coordinates")
    
    # Generate timestamp
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    
    # Format distance for display
    distance_km = distance_m / 1000
    route_title = f"{name} - {distance_km:.1f}km"
    
    # Build trackpoints
    trackpoints = []
    for coord in coordinates:
        # GeoJSON is [lng, lat], GPX uses lat/lon attributes
        lng, lat = coord[0], coord[1]
        trackpoints.append(f'      <trkpt lat="{lat:.6f}" lon="{lng:.6f}"></trkpt>')
    
    trackpoints_xml = "\n".join(trackpoints)
    
    # Assemble GPX document
    gpx = f'''<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="{creator}"
     xmlns="http://www.topografix.com/GPX/1/1"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>{route_title}</name>
    <desc>Generated by DrawMyRoute - AI-powered running routes</desc>
    <time>{timestamp}</time>
  </metadata>
  <trk>
    <name>{route_title}</name>
    <type>running</type>
    <trkseg>
{trackpoints_xml}
    </trkseg>
  </trk>
</gpx>'''
    
    return gpx


def get_gpx_filename(shape_name: str, distance_m: float) -> str:
    """Generate a clean filename for the GPX download."""
    # Sanitize shape name for filename
    safe_name = "".join(c if c.isalnum() else "_" for c in shape_name.lower())
    distance_km = distance_m / 1000
    return f"drawmyroute_{safe_name}_{distance_km:.1f}km.gpx"
